services:
  app:
    image: g4bos/pasteapp:latest
    env_file: .env
    volumes:
      - ./app/uploads:/project/app/uploads
      - static_content:/project/app/static
      - ./certs:/project/certs
    expose:
      - "8000"
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "8000:443"
    volumes:
      - type: bind
        source: ./nginx.conf
        target: /etc/nginx/conf.d/default.conf
        read_only: true
      - ./certs:/etc/nginx/certs
      - static_content:/usr/share/nginx/html/static:ro
    depends_on:
      - app
    restart: unless-stopped

volumes:
  static_content:
